sudo: false

language: python

python:
  - "3.7"

virtualenv:
  system_site_packages: true

#addons:
#  apt:
#    sources:
#      - mopidy-stable
#    packages:
#      - mopidy

env:
  - TOX_ENV=py37
  - TOX_ENV=flake8

before_install:
  - sudo apt-get update
  - pip install Mopidy

install:
  - "pip install tox"

script:
  - "tox -e $TOX_ENV"

after_success:
  - "if [ $TOX_ENV == 'py37' ]; then pip install coveralls; coveralls; fi"


